//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 L2AssistX.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_L2ASSISTX_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_MENU_ROLE                   129
#define IDD_DIALOG_PROPERTY             130
#define IDR_MENU_PROP                   130
#define IDR_MENU_KEYPOP                 130
#define IDI_ICON_FIGHT                  134
#define IDI_ICON_INIT                   135
#define IDI_ICON_BLANK                  136
#define IDI_ICON_WND_H                  138
#define IDI_ICON_DRAG                   139
#define IDI_ICON_EYE                    141
#define IDI_ICON_STOP                   142
#define IDC_CURSOR_SCAN                 143
#define IDD_DIALOG_MESSAGE              144
#define IDI_ICON_DELROLE                147
#define IDI_ICON_DELALLROLE             148
#define IDI_ICON_ADDROLE                149
#define IDI_ICON_ELF64                  150
#define IDC_LIST_ROLE                   1000
#define IDC_LIST_FIGHT                  1001
#define IDC_LIST_BUFFER                 1002
#define IDC_CHECK_ENERGY                1006
#define IDC_COMBO_ENERGY                1007
#define IDC_CHECK_RESURGENCE            1008
#define IDC_CHECK_PICKUP                1010
#define IDC_EDIT_PICKUPCOUNT            1012
#define IDC_EDIT_PICKUPINTERVAL         1013
#define IDC_EDIT_ATTACKTIME             1014
#define IDC_COMBO_TEAMCOUNT             1016
#define IDC_CHECK_RESURGENCEPARTY       1017
#define IDC_CHECK_RESURGENCEREBUFFER    1018
#define IDC_RADIO_NOBILITYLUCKY         1020
#define IDC_RADIO_RECUREEMBLEM          1021
#define IDC_CHECK_MONSTERDIED           1025
#define IDC_EDIT_MONSTORS               1026
#define IDC_CHECK_SHOWMESSAGE           1027
#define IDC_CHECK_ATTACKRANGE           1027
#define IDC_EDIT_MONSTOREXCEPT          1028
#define IDC_CHECK_ATTACKSPECIFIC        1029
#define IDC_EDIT_MONSTORSPECIFIC        1030
#define IDC_CHECK_MARKSTAR              1031
#define IDC_RADIO_ATTACKMONSTOR         1032
#define IDC_RADIO_ATTACKFOLLOW          1033
#define IDC_CHECK_HP1                   1038
#define IDC_EDIT_HP1                    1039
#define IDC_CHECK_HP2                   1041
#define IDC_EDIT_HP2                    1042
#define IDC_CHECK_INVITEPARTNER         1044
#define IDC_CHECK_HP3                   1046
#define IDC_EDIT_HP3                    1047
#define IDC_EDIT_HPPARTNERS             1049
#define IDC_EDIT_TEAMHP                 1050
#define IDC_CHECK_MP1                   1052
#define IDC_EDIT_MP1                    1053
#define IDC_EDIT_HP1KEYCD               1054
#define IDC_COMBO_KEY_FOLLOWATTACK      1055
#define IDC_EDIT_HP2KEYCD               1056
#define IDC_EDIT_DESTTITLE              1057
#define IDC_BUTTON_UPDATETITLE          1058
#define IDC_BUTTON__CLEAR               1058
#define IDC_STATIC_DETECTOR             1059
#define IDC_STATIC_FRAME                1060
#define IDC_EDIT_HP3KEYCD               1060
#define IDC_EDIT_MPPARTNERS             1061
#define IDC_EDIT_TEAMMP                 1062
#define IDC_LIST1                       1062
#define IDC_EDIT_TEAMHPKEYCD            1063
#define IDC_HIDE                        1063
#define IDC_CHECK_EXITTEAMDELAY         1064
#define IDC_CHECK_INVITEPARTNER1        1065
#define IDC_EDIT_EXITTEAM_DELAY         1066
#define IDC_CHECK_INVITEPARTNER2        1067
#define IDC_CHECK_INVITEPARTNER3        1068
#define IDC_CHECK_INVITEPARTNER4        1069
#define IDC_CHECK_INVITEPARTNER5        1070
#define IDC_CHECK_INVITEPARTNER6        1071
#define IDC_EDIT_TEAMPMPKEYCD           1072
#define IDC_EDIT_MP1KEYCD               1073
#define IDC_EDIT_KEY_SPECIFIC1CD        1074
#define IDC_EDIT_KEY_SPECIFIC2CD        1075
#define IDC_EDIT_KEY_SPECIFIC3CD        1076
#define IDC_CHECK_EXCLUDERANGE          1078
#define IDC_EDIT_INVITEPARTNER_DELAY    1079
#define IDC_COMBO_KEY_INVITEPARTNER1    1080
#define IDC_COMBO_KEY_EXITTEAM          1081
#define IDC_COMBO_KEY_HP1               1082
#define IDC_COMBO_KEY_HP2               1083
#define IDC_COMBO_KEY_HP3               1084
#define IDC_COMBO_KEY_MP                1085
#define IDC_COMBO_KEY_TEAMHP            1086
#define IDC_COMBO_KEY_TEAMMP            1087
#define IDC_COMBO_KEY_NOBILITYLUCKY     1088
#define IDC_COMBO_KEY_RECUREEMBLEM      1089
#define IDC_COMBO_KEY_SPECIFIC1         1090
#define IDC_COMBO_KEY_INVITEPARTNER2    1091
#define IDC_COMBO_KEY_INVITEPARTNER3    1092
#define IDC_COMBO_KEY_INVITEPARTNER4    1093
#define IDC_COMBO_KEY_INVITEPARTNER5    1094
#define IDC_COMBO_KEY_INVITEPARTNER6    1095
#define IDC_COMBO_KEY_SPECIFIC2         1096
#define IDC_COMBO_KEY_SPECIFIC3         1097
#define IDC_COMBO_KEY_MARKSTAR          1098
#define IDC_COMBO_KEY_MONSTERDIED       1099
#define IDC_MFCBUTTON_ADD               1101
#define IDC_MFCBUTTON_DEL               1102
#define IDC_MFCBUTTON_CLEAR             1103
#define IDC_COMBO_KEY_PICKUP            1103
#define IDC_MFCBUTTON_STARTALL          1104
#define IDC_MFCBUTTON_STOPALL           1106
#define ID_ROLE_ADD                     32773
#define ID_ROLE_COPY                    32774
#define ID_ROLE_DEL                     32775
#define ID_ROLE_LOAD                    32776
#define ID_ROLE_SAVE                    32777
#define ID_ROLE_START                   32778
#define ID_ROLE_STOP                    32779
#define ID_ROLE_STARTALL                32780
#define ID_ROLE_STOPALL                 32781
#define ID_ROLE_DELALL                  32782
#define ID_KEY_ADD                      32783
#define ID_KEY_DEL                      32784
#define ID_KEY_DELALL                   32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
